# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post", "collection"]
# Output page's full content in RSS.
rssFullContent = false
favicon = "/favicon.ico"

[footer]
since = 2018
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = ""
subtitle = "42는 'The Hitchhiker's Guide to the Galaxy'라는 SF 소설에서 삶, 우주, 그리고 모든 것에 대한 궁극적인 질문에 대한 해답이다."

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
headingAnchor = false
math = true
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 20

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.page]]
type = "search"

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "utterances"

[comments.utterances]
repo = "42jerrykim/42jerrykim.github.io"
issueTerm = "pathname"
label = "BlodComment"
theme = "photon-dark"
